CREATE DATABASE IF NOT EXISTS `dbc`
USE `dbc`;

CREATE TABLE IF NOT EXISTS `emotes_text` (
  `id` int(10) unsigned NOT NULL,
  `internalName` varchar(255) NOT NULL,
  `animationId` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `map` (
  `id` smallint(5) unsigned NOT NULL,
  `internalName` varchar(255) NOT NULL,
  `instanceType` int(10) unsigned NOT NULL,
  `flags` int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `expansion` int(10) unsigned NOT NULL,
  `maxPlayers` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `spells` (
  `id` int(10) unsigned NOT NULL,
  `spellCategory` int(10) unsigned NOT NULL,
  `dispelType` int(10) unsigned NOT NULL,
  `mechanic` int(10) unsigned NOT NULL,
  `attributes` int(10) unsigned NOT NULL,
  `attributesExA` int(10) unsigned NOT NULL,
  `attributesExB` int(10) unsigned NOT NULL,
  `attributesExC` int(10) unsigned NOT NULL,
  `attributesExD` int(10) unsigned NOT NULL,
  `attributesExE` int(10) unsigned NOT NULL,
  `attributesExF` int(10) unsigned NOT NULL,
  `attributesExG` int(10) unsigned NOT NULL,
  `stanceMask` bigint(20) unsigned NOT NULL,
  `stanceExcludeMask` bigint(20) unsigned NOT NULL,
  `targets` int(10) unsigned NOT NULL,
  `targetCreatureType` int(10) unsigned NOT NULL,
  `spellFocusObject` int(10) unsigned NOT NULL,
  `facingCasterFlags` int(10) unsigned NOT NULL,
  `casterAuraState` int(10) unsigned NOT NULL,
  `targetAuraState` int(10) unsigned NOT NULL,
  `casterAuraStateNot` int(10) unsigned NOT NULL,
  `targetAuraStateNot` int(10) unsigned NOT NULL,
  `casterAuraSpell` int(10) unsigned NOT NULL,
  `targetAuraSpell` int(10) unsigned NOT NULL,
  `excludeCasterAuraSpell` int(10) unsigned NOT NULL,
  `excludeTargetAuraSpell` int(10) unsigned NOT NULL,
  `castingTimeIndex` int(10) unsigned NOT NULL,
  `recoveryTime` int(10) unsigned NOT NULL,
  `categoryRecoveryTime` int(10) unsigned NOT NULL,
  `interruptFlags` int(10) unsigned NOT NULL,
  `auraInterruptFlags` int(10) unsigned NOT NULL,
  `channelInterruptFlags` int(10) unsigned NOT NULL,
  `procFlags` int(10) unsigned NOT NULL,
  `procChance` int(10) unsigned NOT NULL,
  `procCharges` int(10) unsigned NOT NULL,
  `maxLevel` int(10) unsigned NOT NULL,
  `baseLevel` int(10) unsigned NOT NULL,
  `spellLevel` int(10) unsigned NOT NULL,
  `durationIndex` int(10) unsigned NOT NULL,
  `powerType` int(10) NOT NULL,
  `manaCost` int(10) unsigned NOT NULL,
  `manaCostPerLevel` int(10) unsigned NOT NULL,
  `manaPerSecond` int(10) unsigned NOT NULL,
  `manaPerSecondPerLevel` int(10) unsigned NOT NULL,
  `rangeIndex` int(10) unsigned NOT NULL,
  `speed` float NOT NULL,
  `modalNextSpell` int(10) unsigned NOT NULL,
  `stackAmount` int(10) unsigned NOT NULL,
  `totem1` int(10) unsigned NOT NULL,
  `totem2` int(10) unsigned NOT NULL,
  `reagent1` int(10) NOT NULL,
  `reagent2` int(10) NOT NULL,
  `reagent3` int(10) NOT NULL,
  `reagent4` int(10) NOT NULL,
  `reagent5` int(10) NOT NULL,
  `reagent6` int(10) NOT NULL,
  `reagent7` int(10) NOT NULL,
  `reagent8` int(10) NOT NULL,
  `reagentCount1` int(10) NOT NULL,
  `reagentCount2` int(10) NOT NULL,
  `reagentCount3` int(10) NOT NULL,
  `reagentCount4` int(10) NOT NULL,
  `reagentCount5` int(10) NOT NULL,
  `reagentCount6` int(10) NOT NULL,
  `reagentCount7` int(10) NOT NULL,
  `reagentCount8` int(10) NOT NULL,
  `equippedItemClass` int(10) NOT NULL,
  `equippedItemSubClassMask` int(10) NOT NULL,
  `equippedItemInventoryTypeMask` int(10) NOT NULL,
  `effect1` int(10) unsigned NOT NULL,
  `effect2` int(10) unsigned NOT NULL,
  `effect3` int(10) unsigned NOT NULL,
  `effectDieSides1` int(10) NOT NULL,
  `effectDieSides2` int(10) NOT NULL,
  `effectDieSides3` int(10) NOT NULL,
  `effectRealPointsPerLevel1` float NOT NULL,
  `effectRealPointsPerLevel2` float NOT NULL,
  `effectRealPointsPerLevel3` float NOT NULL,
  `effectBasePoints1` int(10) NOT NULL,
  `effectBasePoints2` int(10) NOT NULL,
  `effectBasePoints3` int(10) NOT NULL,
  `effectMechanic1` int(10) unsigned NOT NULL,
  `effectMechanic2` int(10) unsigned NOT NULL,
  `effectMechanic3` int(10) unsigned NOT NULL,
  `effectImplicitTargetA1` int(10) unsigned NOT NULL,
  `effectImplicitTargetA2` int(10) unsigned NOT NULL,
  `effectImplicitTargetA3` int(10) unsigned NOT NULL,
  `effectImplicitTargetB1` int(10) unsigned NOT NULL,
  `effectImplicitTargetB2` int(10) unsigned NOT NULL,
  `effectImplicitTargetB3` int(10) unsigned NOT NULL,
  `effectRadiusIndex1` int(10) unsigned NOT NULL,
  `effectRadiusIndex2` int(10) unsigned NOT NULL,
  `effectRadiusIndex3` int(10) unsigned NOT NULL,
  `effectApplyAuraName1` int(10) unsigned NOT NULL,
  `effectApplyAuraName2` int(10) unsigned NOT NULL,
  `effectApplyAuraName3` int(10) unsigned NOT NULL,
  `effectAuraPeriod1` int(10) unsigned NOT NULL,
  `effectAuraPeriod2` int(10) unsigned NOT NULL,
  `effectAuraPeriod3` int(10) unsigned NOT NULL,
  `effectAmplitude1` float NOT NULL,
  `effectAmplitude2` float NOT NULL,
  `effectAmplitude3` float NOT NULL,
  `effectChainTarget1` int(10) unsigned NOT NULL,
  `effectChainTarget2` int(10) unsigned NOT NULL,
  `effectChainTarget3` int(10) unsigned NOT NULL,
  `effectItemType1` int(10) unsigned NOT NULL,
  `effectItemType2` int(10) unsigned NOT NULL,
  `effectItemType3` int(10) unsigned NOT NULL,
  `effectMiscValueA1` int(11) NOT NULL,
  `effectMiscValueA2` int(11) NOT NULL,
  `effectMiscValueA3` int(11) NOT NULL,
  `effectMiscValueB1` int(11) NOT NULL,
  `effectMiscValueB2` int(11) NOT NULL,
  `effectMiscValueB3` int(11) NOT NULL,
  `effectTriggerSpell1` int(10) unsigned NOT NULL,
  `effectTriggerSpell2` int(10) unsigned NOT NULL,
  `effectTriggerSpell3` int(10) unsigned NOT NULL,
  `effectPointsPerComboPoint1` float NOT NULL,
  `effectPointsPerComboPoint2` float NOT NULL,
  `effectPointsPerComboPoint3` float NOT NULL,
  `effectSpellClassMaskA1` int(10) unsigned NOT NULL,
  `effectSpellClassMaskA2` int(10) unsigned NOT NULL,
  `effectSpellClassMaskA3` int(10) unsigned NOT NULL,
  `effectSpellClassMaskB1` int(10) unsigned NOT NULL,
  `effectSpellClassMaskB2` int(10) unsigned NOT NULL,
  `effectSpellClassMaskB3` int(10) unsigned NOT NULL,
  `effectSpellClassMaskC1` int(10) unsigned NOT NULL,
  `effectSpellClassMaskC2` int(10) unsigned NOT NULL,
  `effectSpellClassMaskC3` int(10) unsigned NOT NULL,
  `spellVisual1` int(10) unsigned NOT NULL,
  `spellVisual2` int(10) unsigned NOT NULL,
  `spellIconID` int(10) unsigned NOT NULL,
  `activeIconID` int(10) unsigned NOT NULL,
  `spellPriority` int(10) unsigned NOT NULL,
  `spellName` varchar(255) NOT NULL,
  `spellSubText` varchar(255) NOT NULL,
  `manaCostPercentage` int(10) unsigned NOT NULL,
  `startRecoveryCategory` int(10) unsigned NOT NULL,
  `startRecoveryTime` int(10) unsigned NOT NULL,
  `maxTargetLevel` int(10) unsigned NOT NULL,
  `spellClassSet` int(10) unsigned NOT NULL,
  `spellClassMask1` int(10) unsigned NOT NULL,
  `spellClassMask2` int(10) unsigned NOT NULL,
  `spellClassMask3` int(10) unsigned NOT NULL,
  `maxTargets` int(10) unsigned NOT NULL,
  `defenseType` int(10) unsigned NOT NULL,
  `preventionType` int(10) unsigned NOT NULL,
  `stanceBarOrder` int(10) unsigned NOT NULL,
  `effectChainAmplitude1` float NOT NULL,
  `effectChainAmplitude2` float NOT NULL,
  `effectChainAmplitude3` float NOT NULL,
  `minFactionId` int(10) unsigned NOT NULL,
  `minReputation` int(10) unsigned NOT NULL,
  `requiredAuraVision` int(10) unsigned NOT NULL,
  `totemCategory1` int(10) unsigned NOT NULL,
  `totemCategory2` int(10) unsigned NOT NULL,
  `requiredAreaId` int(11) NOT NULL,
  `schoolMask` int(10) unsigned NOT NULL,
  `runeCostID` int(10) unsigned NOT NULL,
  `spellMissileID` int(10) unsigned NOT NULL,
  `powerDisplayID` int(11) NOT NULL,
  `effectBonusMultiplier1` float NOT NULL,
  `effectBonusMultiplier2` float NOT NULL,
  `effectBonusMultiplier3` float NOT NULL,
  `spellDescriptionVariableID` int(10) unsigned NOT NULL,
  `spellDifficultyID` int(10) unsigned NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
