include_guard(GLOBAL)

# Setup Cached Options
set(NOVUSCORE_BUILD_ENGINE ON CACHE BOOL "Builds the Engine Project")
set(NOVUSCORE_BUILD_GAME ON CACHE BOOL "Builds the Game Project")
set(NOVUSCORE_BUILD_SERVER OFF CACHE BOOL "Builds the Server Project")

# Setup Non-Cached Options
set(CMAKE_CONFIGURATION_TYPES Debug Release RelWithDebInfo CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_DISABLE_SOURCE_CHANGES ON)
set(CMAKE_DISABLE_IN_SOURCE_BUILD ON)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Bin/Libs)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Bin)

set(NOVUSCORE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set(NOVUSCORE_BUILD_DIR ${CMAKE_BINARY_DIR}/bin)
set(NOVUSCORE_SETUP ON)